userLogin = "templeloginapi"
addTempleapi = "templeaddapi"
listTempleapi = "templelistapi"
createTempleAdminapi = "templeadminapi"
listTempleAdminapi = "templeadminlistapi"
createAccountapi = "templecreateaccountapi"
listAccountapi = "templeaccountlistapi"
accStatement = "templeaccstatmentapi"
createFinAdminapi="templecreatefinadminapi"
createPoojaapi="templecreatepoojaapi"
listPoojaapi="templelistpoojaapi"
createOfferingapi="templecreateofferingapi"
listOfferingapi="templelistofferingapi"
createPrasadamapi="templecreateprasadamapi"
listPrasadamapi="templelistprasadamapi"
createDietyapi="templecreatedietyapi"
listDietyapi="templelistdietyapi"
createHistoryapi="templecreateHistoryapi"


